# many-protocol/specification CI
version: 2.1

#orbs:
#  rust: circleci/rust@1.6.0

jobs:
  validate_cddl:
    docker:
      - image: cimg/base:2022.10
    resource_class: small
    steps:
      - checkout
      - run:
          name: validating merged cddl
          command: |
            find * -iname \*.cddl | xargs cat > temp.cddl
            cddl-linux-amd64 compile-cddl --cddl temp.cddl

commands:
  install-deps:
    steps:
      - run:
          name: install cddl-linux-amd64
          command: wget https://github.com/anweiss/cddl/releases/download/0.9.0/cddl-linux-amd64.tar.gz -O - | sudo tar -xz -C /usr/local/bin

workflows:
  validate_cddl:
    jobs:
      - validate_cddl:
          pre-steps:
            - install-deps