# many-protocol/specification CI
version: 2.1

#orbs:
#  rust: circleci/rust@1.6.0

jobs:
  validate_cddl:
    docker:
      - image: cimg/base:2022.10
    resource_class: small
    steps:
      - checkout
      - run:
          name: validate cddl
          command: |
            find * -iname \*.cddl | xargs cat > temp.cddl
            docker pull ghcr.io/anweiss/cddl-cli:latest
            docker run -it --rm -v $PWD:/ll-work -w /ll-work ghcr.io/anweiss/cddl-cli:latest compile-cddl --cddl temp.cddl

workflows:
  validate_cddl:
    jobs:
      - validate_cddl