on:
  - push
  - pull_request

name: CDDL

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build CDDL
        run: bash scripts/make_cddl.bash ./temp.cddl
      - uses: docker://ghcr.io/anweiss/cddl-cli:latest
        with:
          args: compile-cddl --cddl temp.cddl
